import { createHash } from 'crypto';
import { readFileSync, writeFileSync, existsSync } from 'fs';
import yaml from 'js-yaml';

const LOCK_FILE = 'bundle.lock';

export function readLock() {
  if (!existsSync(LOCK_FILE)) return {};
  return yaml.load(readFileSync(LOCK_FILE, 'utf8')) || {};
}

export function writeLock(lock) {
  const header = '# bundle.lock — auto-generated by torque resolve. Do not edit manually.\n';
  writeFileSync(LOCK_FILE, header + yaml.dump(lock, { lineWidth: -1 }));
}

export function getLockEntry(lock, bundleName) {
  return lock[bundleName] || null;
}

export function setLockEntry(lock, bundleName, entry) {
  lock[bundleName] = {
    source: entry.source,
    commit: entry.commit,
    resolved_at: new Date().toISOString(),
    ...(entry.manifest_hash != null && { manifest_hash: entry.manifest_hash }),
    ...(entry.logic_hash != null && { logic_hash: entry.logic_hash }),
  };
}

export function removeLockEntry(lock, bundleName) {
  delete lock[bundleName];
}

/**
 * Compute a SHA-256 hash of a file's contents.
 * Returns null if the file does not exist.
 * @param {string} filePath
 * @returns {string|null}
 */
export function computeFileHash(filePath) {
  if (!existsSync(filePath)) return null;
  const content = readFileSync(filePath);
  return createHash('sha256').update(content).digest('hex');
}
